version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: student-notes-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: student_notes_platform
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: student-notes-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/student_notes_platform
      - JWT_SECRET=your_jwt_secret_here
      - CLIENT_ORIGIN=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: student-notes-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongodb_data:
